server:
  port: 8071

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/resqnet
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: true